In [27]:
import numpy as np

In [28]:
solar_data=np.loadtxt('solar.txt')

In [29]:
print(solar_data)

[[277.97178749 290.87848694  16.27913217]
 [276.79002882   0.          92.19335012]
 [196.02083865 126.81410304 127.24963504]
 ...
 [281.2492984  145.13885509  68.75927169]
 [308.79714745 109.84031278 135.8464653 ]
 [255.70751034 122.4024413  117.49570871]]


In [30]:
print(solar_data.shape)

(365, 3)


In [57]:
# How many watts were generated all year?
solar_data.sum()
#A total of 218,010 watts were generated all year


218010.26201750195

In [40]:
# What were the most watts generated in the morning, afternoon, and evening? The least?
print(solar_data[:,0].max()) #Most watts in the morning
print(solar_data[:,1].max()) #Most watts in the afternoon
print(solar_data[:,2].max()) #Most watts in the evening

print(solar_data[:,0].min()) #Least watts in morning
print(solar_data[:,1].min()) #Least watts in afternoon
print(solar_data[:,2].min()) #Least watts in evening

446.4043420712958
450.23976606026287
247.0150989425381
166.23303072555183
0.0
0.0


In [46]:
#Total number watts generated on January afternoons
total=solar_data[1:32,1].sum()
avg=total/31
print(total)
#Average watts generated on January afternoon
print(avg)

6553.9471035217
211.4176485007


In [56]:
#Total days the system generated fewer than 500 watts total(morning, afternoon and evening values are added up for each day)
solar_data[solar_data[:,0:3].sum(axis=1) <500].shape


(89, 3)

In [65]:
#Average watts generated all year
print(solar_data.mean())
#218010.26/365
#Average watts generated in morning all year
print(solar_data[:,0].mean())
#Average watts generated in afternoon all year
print(solar_data[:,1].mean())
#Average watts generated in evening all year
print(solar_data[:,2].mean())

199.0961296963488
300.38834890807675
198.39523217279387
98.5048080081758


199.0961296963488


In [ ]:
def matrix_add_2d(a,b):
  result=[]

  for i in range(len(a)):
    result.append([])
    for j in range(len(a[0])):
      result[i].append(a[i][j]+b[i][j])
  return result

In [4]:
small_matrix = [
    [1, 2, 3],
    [4, 5, 6]
]

%timeit matrix_add_2d(small_matrix, small_matrix)

1.21 µs ± 273 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [11]:
 red= np.array(small_matrix) + np.array(small_matrix)
 %timeit red

14.3 ns ± 3.71 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [7]:
medium_matrix = [
    [1,  2,  3,  4,  5],
    [6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
]

%timeit matrix_add_2d(medium_matrix, medium_matrix)


3.1 µs ± 89.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
blue= np.array(medium_matrix) + np.array(medium_matrix)
%timeit blue


13.3 ns ± 1.11 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [10]:
very_large_matrix = [[j for j in range(1000)] for i in range(1000)]
%timeit matrix_add_2d(very_large_matrix, very_large_matrix)

108 ms ± 1.23 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [12]:
purple= np.array(very_large_matrix) + np.array(very_large_matrix)
%timeit purple

14.4 ns ± 3.06 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [11]:
matrix_a = [[1, 2, 3], [4, 5]]
matrix_b = [[6, 7, 8], [9, 10, 11]]

print(matrix_add_2d(matrix_a, matrix_b))  # Error! Different row sizes.


IndexError: list index out of range

In [13]:
a = np.array([[1, 2, 3], [4, 5]])  # Creates an object array, not a 2D array
b = np.array([[6, 7, 8], [9, 10, 11]])

print(a + b)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [16]:
a = np.array ( [
[ 1 , 1 , 2 ] ,
[ 3 , 2 , 1 ] ,
[ 1 , 9 , 1 ]
] )
b = np.array( [
[ 1 ] ,
[ 2 ] ,
[ 3 ]
] )

print(a + b)

[[ 2  2  3]
 [ 5  4  3]
 [ 4 12  4]]


In [20]:
a = np.array ( [
[
[ 1 , 2 ] ,
[ 3 , 1 ]
] ,
[
[ 8 , 7 ] ,
[ 9 , 1 ]
]
] )
b = np.array( [ 10 , 11 ] )

print(a + b)

[[[11 13]
  [13 12]]

 [[18 18]
  [19 12]]]


In [23]:
a = np.array( [ 1 , 2 , 3 ] )
b = np.array( [
[ 10 ] ,
[ 11 ] ,
[ 12 ]
] )

print(a + b)

[[11 12 13]
 [12 13 14]
 [13 14 15]]


In [25]:
a = np.array( [
[
[ 1 , 2 ] ,
[ 3 , 1 ]
] ,
[
[ 8 , 7 ] ,
[ 9 , 1 ]
]
] )
b = np.array( [ 10 , 11 , 12 , 13 ] )

print(a+b)

ValueError: operands could not be broadcast together with shapes (2,2,2) (4,) 

In [26]:
a = np.array( [
[
[
[ 1 ] ,
]
] ,
[
[
[ 2 ]
]
]
] )
b = np.array( [ 3 , 4 ] )

print(a+b)

[[[[4 5]]]


 [[[5 6]]]]
